#----------------------------------------------------------------------
#                      Makefile to build libcjson2
#                 Copyright (c) 2008 American Megatrends Inc 
#-----------------------------------------------------------------------

#---------------------- Change according to your files ----------------------------------
LIBRARY_NAME 	= libcjson2
SRC 		= cJSON.c		 	    # Source File

CFLAGS += -I${SPXINC}/global

#----------------------------------------------------------------------------------------
include ${TOOLDIR}/rules/Rules.make.libs
